name: Test

on: [push, pull_request]

jobs:
  publishserver:
    name: "Publish Server"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: server
          platforms: linux/amd64
          push: false
          tags: lavalleeale/remoteftc:latest

  electron:
    defaults:
      run:
        shell: bash
        working-directory: web
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000
      - name: Build
        run: |
          yarn electron:build
