name: Build

on: [push, pull_request]

jobs:
  buildserver:
    name: "Build Server"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: server
          platforms: linux/amd64
          push: false
          tags: lavalleeale/remoteftc:latest
  buildelectron:
    name: "Build Electron"
    defaults:
      run:
        shell: bash
        working-directory: web
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: 16.13

      - uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm electron:build

      - name: Archive macOS production artifacts
        if: ${{matrix.os == 'macos-latest'}}
        uses: actions/upload-artifact@v2
        with:
          name: RemoteFTC-mac-x64
          path: web/dist/RemoteFTC-mac-x64.dmg

      - name: Archive Linux production artifacts
        if: ${{matrix.os == 'ubuntu-latest'}}
        uses: actions/upload-artifact@v2
        with:
          name: RemoteFTC-linux-x86_64
          path: web/dist/RemoteFTC-linux-x86_64.AppImage

      - name: Archive Windows production artifacts
        if: ${{matrix.os == 'windows-latest'}}
        uses: actions/upload-artifact@v2
        with:
          name: RemoteFTC-win-x64
          path: web/dist/RemoteFTC-win-x64.exe
  test:
    name: "Test with Cypress"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dependancy caching
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.27.1
      - name: Install dependencies
        run: pnpm --dir web i

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: pnpm build
          start: pnpm start
          working-directory: web
