name: Build-Electron

on: [push, pull_request]

jobs:
  build-electron:
    defaults:
      run:
        shell: bash
        working-directory: web
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: 16.13

      - uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm electron:build
      
      - name: Archive macOS production artifacts
        if: ${{matrix.os == 'macos-latest'}}
        uses: actions/upload-artifact@v2
        with:
          name: RemoteFTC-mac-x64
          path: web/dist/RemoteFTC-mac-x64.dmg

      - name: Archive Linux production artifacts
        if: ${{matrix.os == 'ubuntu-latest'}}
        uses: actions/upload-artifact@v2
        with:
          name: RemoteFTC-linux-x86_64
          path: web/dist/RemoteFTC-linux-x86_64.AppImage

      - name: Archive Windows production artifacts
        if: ${{matrix.os == 'windows-latest'}}
        uses: actions/upload-artifact@v2
        with:  
          name: RemoteFTC-win-x64
          path: web/dist/RemoteFTC-win-x64.exe

      